### Задание 1

In [2]:
import numpy as np

In [4]:
a = np.array([[1, 6],
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7]])
print(a)

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]


In [3]:
a. shape

(5, 2)

In [16]:
np.mean(a, axis=0, out = mean_a)


array([2. , 8.4])

### Задание 2

In [18]:
a_centered = a - mean_a
print(a_centered)

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


In [19]:
a_centered.shape

(5, 2)

### Задание 3


In [23]:
x1 = np.array([-1, 0, 1, 1, -1])
x2 = np.array([-2.4, -0.4, 2.6, 1.6, -1.4])
a_centered_sp = np.dot(x1, x2)
print(a_centered_sp)

8.0


In [25]:
b = a_centered_sp / (a_centered.shape[0] - 1)
print(b)

2.0


### Задание 4**

In [5]:
np.cov(a.T)[0, 1]

2.0


### Тема “Работа с данными в Pandas”


### Задание 1

In [52]:
import pandas as pd


In [53]:
authors = pd.DataFrame({'author_id':[1, 2, 3],
            'author_name':['Тургенев', 'Чехов', 'Островский']})


print(authors)

   author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский


In [59]:
book = pd.DataFrame({'author_id':[1, 1, 1, 2, 2, 3, 3], 
                     'book_title':['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'], 
                     'price':[450, 300, 350, 500, 450, 370, 290]}, 
                    columns=['author_id', 'book_title', 'price'])
print(book)

   author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290


In [60]:
book = pd.DataFrame({'author_id':[1, 1, 1, 2, 2, 3, 3], 
                     'book_title':['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'], 
                     'price':[450, 300, 350, 500, 450, 370, 290]}, 
                    columns=['author_id', 'book_title', 'price'])
print(book)

   author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290


### Задание 2

In [61]:
authors_price = pd.merge(authors, book, on='author_id', how='outer')
print(authors_price)

   author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290


### Задание 3

In [62]:
top5 = authors_price.nlargest(5, "price")
print(top5)


   author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350


### Задание 4

In [67]:
authors_stat = authors_price.groupby('author_name').agg({'price':['min', 'max', 'mean']})
print(authors_stat)

            price                 
              min  max        mean
author_name                       
Островский    290  370  330.000000
Тургенев      300  450  366.666667
Чехов         450  500  475.000000


### Задание 5**